# Generated by Django 3.2 on 2021-04-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredResults2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.FloatField()),
                ('Fertilizers', models.FloatField()),
                ('Rainfall', models.FloatField()),
                ('Storage', models.FloatField()),
                ('Electricity', models.FloatField()),
                ('yeild', models.FloatField()),
                ('prices', models.FloatField()),
            ],
        ),
    ]
